spring.datasource.url=jdbc:mysql://localhost:3306/transpoin
spring.datasource.username=transPoin
spring.datasource.password=transpoinprojectpbo12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# Upload file config
upload.dir=uploads/bukti
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Static resource untuk serve uploaded files
spring.web.resources.static-locations=classpath:/static/,file:uploads/
